{{- $secretName := include "llmos-agents.langfuse.init-name" . }}
{{- $secret := lookup "v1" "Secret" .Release.Namespace $secretName }}
{{- $existingPublicKey := "" }}
{{- $existingSecretKey := "" }}
{{- $existingUserPassword := "" }}
{{- $existingSalt := "" }}
{{- $existingNextAuth := "" }}
{{- $existingS3RootUser := "" }}
{{- $existingS3RootPassword := "" }}
{{- if and $secret (index $secret.data "LANGFUSE_INIT_PROJECT_PUBLIC_KEY") }}
{{- $existingPublicKey = index $secret.data "LANGFUSE_INIT_PROJECT_PUBLIC_KEY" | b64dec }}
{{- $existingSecretKey = index $secret.data "LANGFUSE_INIT_PROJECT_SECRET_KEY" | b64dec }}
{{- $existingUserPassword = index $secret.data "LANGFUSE_INIT_USER_PASSWORD" | b64dec }}
{{- $existingSalt = index $secret.data "LANGFUSE_SALT" | b64dec }}
{{- $existingNextAuth = index $secret.data "LANGFUSE_NEXT_AUTH" | b64dec }}
{{- $existingS3RootUser = index $secret.data "LANGFUSE_S3_ROOT_USER" | b64dec }}
{{- $existingS3RootPassword = index $secret.data "LANGFUSE_S3_ROOT_PASSWORD" | b64dec }}
{{- end }}
{{- $finalPublicKey := default (printf "pk-lf-%s" (randAlphaNum 30)) $existingPublicKey }}
{{- $finalSecretKey := default (printf "sk-lf-%s" (randAlphaNum 30)) $existingSecretKey }}
{{- $finalUserPassword := default (printf "sk-%s" (randAlphaNum 15)) $existingUserPassword }}
{{- $finalSalt := default (randAlphaNum 30) $existingSalt }}
{{- $finalNextAuth := default (randAlphaNum 30) $existingNextAuth }}
{{- $finalS3RootUser := default ("root") $existingS3RootUser }}
{{- $finalS3RootPassword := default (randAlphaNum 15) $existingS3RootPassword }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $secretName }}
  labels:
    {{- include "llmos-agents.labels" . | nindent 4 }}
    app.kubernetes.io/component: "langfuse"
stringData:
  # Headless init config
  LANGFUSE_INIT_ORG_ID:       "llmos"
  LANGFUSE_INIT_ORG_NAME:     "LLMOS"
  LANGFUSE_INIT_PROJECT_ID:   "llmos-agents"
  LANGFUSE_INIT_PROJECT_NAME: "LLMOS Agents"
  LANGFUSE_INIT_PROJECT_PUBLIC_KEY:  {{ $finalPublicKey }}
  LANGFUSE_INIT_PROJECT_SECRET_KEY:  {{ $finalSecretKey }}
  LANGFUSE_INIT_USER_PASSWORD:  {{ $finalUserPassword }}

  # Salt for encryption
  LANGFUSE_SALT: {{ $finalSalt }}
  LANGFUSE_NEXT_AUTH: {{ $finalNextAuth }}

  # S3 auth config
  LANGFUSE_S3_ROOT_USER: {{ $finalS3RootUser }}
  LANGFUSE_S3_ROOT_PASSWORD: {{ $finalS3RootPassword }}