{{- $secretName := include "llmos-agents.langfuse.init-name" . }}
{{- $secret := lookup "v1" "Secret" .Release.Namespace $secretName }}
{{- $existingPublicKey := "" }}
{{- $existingSecretKey := "" }}
{{- $existingSalt := "" }}
{{- $existingNextAuth := "" }}
{{- if and $secret (index $secret.data "LANGFUSE_INIT_PROJECT_PUBLIC_KEY") }}
{{- $existingPublicKey = index $secret.data "LANGFUSE_INIT_PROJECT_PUBLIC_KEY" | b64dec }}
{{- $existingSecretKey = index $secret.data "LANGFUSE_INIT_PROJECT_SECRET_KEY" | b64dec }}
{{- $existingSalt = index $secret.data "LANGFUSE_SALT" | b64dec }}
{{- $existingNextAuth = index $secret.data "LANGFUSE_NEXT_AUTH" | b64dec }}
{{- end }}
{{- $finalPulicKey := default (printf "pk-lf-%s" (randAlphaNum 30)) $existingPublicKey }}
{{- $finalSecretKey := default (printf "sk-lf-%s" (randAlphaNum 30)) $existingSecretKey }}
{{- $finalSalt := default (randAlphaNum 30) $existingSalt }}
{{- $finalNextAuth := default (randAlphaNum 30) $existingNextAuth }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $secretName }}
  labels:
    {{- include "llmos-agents.labels" . | nindent 4 }}
    app.kubernetes.io/component: "langfuse"
stringData:
  # Headless init config
  LANGFUSE_INIT_ORG_ID:       "llmos"
  LANGFUSE_INIT_ORG_NAME:     "LLMOS"
  LANGFUSE_INIT_PROJECT_ID:   "llmos-agents"
  LANGFUSE_INIT_PROJECT_NAME: "LLMOS Agents"
  LANGFUSE_INIT_PROJECT_PUBLIC_KEY:  {{ $finalPulicKey }}
  LANGFUSE_INIT_PROJECT_SECRET_KEY:  {{ $finalSecretKey }}

  # Salt for encryption
  LANGFUSE_SALT: {{ $finalSalt }}
  LANGFUSE_NEXT_AUTH: {{ $finalNextAuth }}
