remote: upstream
target-branch: main
chart-dirs:
  - charts
chart-repos:
  - bitnami=https://charts.bitnami.com/bitnami
  - grafana=https://grafana.github.io/helm-charts
  - prometheus-community=https://prometheus-community.github.io/helm-charts
github-groups: true
helm-extra-args: --timeout 600s