{
 "title": "Ray / Data Dashboard",
 "tags": [ "kuberay:1.2.2" ],
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "SessionName",
    "query": {
     "query": "label_values(ray_data_allocated_bytes{}, SessionName)"
    }
   },
   {
    "name": "DatasetID",
    "query": {
     "query": "label_values(ray_data_allocated_bytes{}, dataset)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Bytes Spilled",
   "type": "graph",
   "description": "Amount spilled by dataset operators. DataContext.enable_get_object_locations_for_metrics must be set to True to report this metric",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(ray_data_spilled_bytes{dataset=~\"$DatasetID\",SessionName=~\"$SessionName\",}) by (dataset, operator)",
     "legendFormat": "Bytes Spilled: {{dataset}}, {{operator}}"
    }
   ]
  },
  {
   "title": "Bytes Allocated",
   "type": "graph",
   "description": "Amount allocated by dataset operators.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(ray_data_allocated_bytes{dataset=~\"$DatasetID\",SessionName=~\"$SessionName\",}) by (dataset, operator)",
     "legendFormat": "Bytes Allocated: {{dataset}}, {{operator}}"
    }
   ]
  },
  {
   "title": "Bytes Freed",
   "type": "graph",
   "description": "Amount freed by dataset operators.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(ray_data_freed_bytes{dataset=~\"$DatasetID\",SessionName=~\"$SessionName\",}) by (dataset, operator)",
     "legendFormat": "Bytes Freed: {{dataset}}, {{operator}}"
    }
   ]
  },
  {
   "title": "Object Store Memory",
   "type": "graph",
   "description": "Amount of memory store used by dataset operators.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(ray_data_current_bytes{dataset=~\"$DatasetID\",SessionName=~\"$SessionName\",}) by (dataset, operator)",
     "legendFormat": "Current Usage: {{dataset}}, {{operator}}"
    }
   ]
  },
  {
   "title": "CPUs (logical slots)",
   "type": "graph",
   "description": "Logical CPUs allocated to dataset operators.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 2 },
   "yaxes": [
    { "format": "cores" }
   ],
   "targets": [
    {
     "expr": "sum(ray_data_cpu_usage_cores{dataset=~\"$DatasetID\",SessionName=~\"$SessionName\",}) by (dataset, operator)",
     "legendFormat": "CPU Usage: {{dataset}}, {{operator}}"
    }
   ]
  },
  {
   "title": "GPUs (logical slots)",
   "type": "graph",
   "description": "Logical GPUs allocated to dataset operators.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 2 },
   "yaxes": [
    { "format": "cores" }
   ],
   "targets": [
    {
     "expr": "sum(ray_data_gpu_usage_cores{dataset=~\"$DatasetID\",SessionName=~\"$SessionName\",}) by (dataset, operator)",
     "legendFormat": "GPU Usage: {{dataset}}, {{operator}}"
    }
   ]
  },
  {
   "title": "Bytes Outputted",
   "type": "graph",
   "description": "Total bytes outputted by dataset operators.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 3 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(ray_data_output_bytes{dataset=~\"$DatasetID\",SessionName=~\"$SessionName\",}) by (dataset, operator)",
     "legendFormat": "Bytes Outputted: {{dataset}}, {{operator}}"
    }
   ]
  },
  {
   "title": "Rows Outputted",
   "type": "graph",
   "description": "Total rows outputted by dataset operators.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 3 },
   "yaxes": [
    { "format": "rows" }
   ],
   "targets": [
    {
     "expr": "sum(ray_data_output_rows{dataset=~\"$DatasetID\",SessionName=~\"$SessionName\",}) by (dataset, operator)",
     "legendFormat": "Rows Outputted: {{dataset}}, {{operator}}"
    }
   ]
  },
  {
   "title": "Block Generation Time",
   "type": "graph",
   "description": "Time spent generating blocks.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 4 },
   "yaxes": [
    { "format": "seconds" }
   ],
   "targets": [
    {
     "expr": "sum(ray_data_block_generation_seconds{dataset=~\"$DatasetID\",SessionName=~\"$SessionName\",}) by (dataset, operator)",
     "legendFormat": "Block Generation Time: {{dataset}}, {{operator}}"
    }
   ]
  },
  {
   "title": "Iteration Blocked Time",
   "type": "graph",
   "description": "Seconds user thread is blocked by iter_batches()",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 4 },
   "yaxes": [
    { "format": "seconds" }
   ],
   "targets": [
    {
     "expr": "sum(ray_data_iter_total_blocked_seconds{dataset=~\"$DatasetID\",SessionName=~\"$SessionName\",}) by (dataset)",
     "legendFormat": "Seconds: {{dataset}}"
    }
   ]
  },
  {
   "title": "Iteration User Time",
   "type": "graph",
   "description": "Seconds spent in user code",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 5 },
   "yaxes": [
    { "format": "seconds" }
   ],
   "targets": [
    {
     "expr": "sum(ray_data_iter_user_seconds{dataset=~\"$DatasetID\",SessionName=~\"$SessionName\",}) by (dataset)",
     "legendFormat": "Seconds: {{dataset}}"
    }
   ]
  }
 ]
}