{{- if .Values.modelServiceExporter.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels: {{ include "kube-prometheus-stack.labels" . | nindent 4 }}
  name: llmos-model-service
  namespace: {{ include "kube-prometheus-stack.namespace" . }}
spec:
  endpoints:
  - interval: 5s
    path: /metrics
    port: http
    relabelings:
    - action: replace
      regex: (.*)
      sourceLabels:
        - __meta_kubernetes_endpoints_label_ml_llmos_ai_model_service_name
      targetLabel: model_service_name
    - action: replace
      regex: (.*)
      sourceLabels:
        - __meta_kubernetes_pod_node_name
      targetLabel: node_name
    - action: replace
      regex: (.*)
      sourceLabels:
        - __meta_kubernetes_pod_host_ip
      targetLabel: node_ip
    - action: replace
      regex: (GPU-[^,]*),.*
      sourceLabels:
        - __meta_kubernetes_pod_annotation_hami_io_vgpu_devices_allocated
      targetLabel: device_id
    - action: replace
      regex: GPU-[^,]*,([^,]*),.*
      replacement: $1
      sourceLabels:
        - __meta_kubernetes_pod_annotation_hami_io_vgpu_devices_allocated
      targetLabel: device_type
  jobLabel: ml.llmos.ai/type
  namespaceSelector:
    any: true
  selector:
    matchLabels:
      ml.llmos.ai/type: model-service
{{- end }}