name: Lint and Test Charts

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

env:
  UPSTREAM_REPO: ${{ vars.UPSTREAM_REPO || 'https://github.com/llmos-ai/charts.git' }}

jobs:
  lint-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set Up Upstream Repo
        run: |
          echo "UPSTREAM_REPO=$UPSTREAM_REPO"
          git remote add upstream "$UPSTREAM_REPO"
          git fetch upstream

      - name: Set up Helm
        uses: azure/setup-helm@v4
        with:
          version: v3.12.0

      - uses: actions/setup-python@v5
        with:
          python-version: '3.13.1'

      - name: Set up chart-testing
        uses: helm/chart-testing-action@v2.6.1

      - name: Run chart-testing (list-changed)
        id: list-changed
        run: |
          changed="$(ct list-changed --config .github/linters/ct.yaml)"
          if [[ -n "$changed" ]]; then
            echo "changed=true" >> "$GITHUB_OUTPUT"
            echo "changed_list=\"${changed//$'\n'/ }\"" >> "$GITHUB_OUTPUT"
          fi

      - name: Run chart-testing (lint)
        run: ct lint --config .github/linters/ct.yaml

      - name: Create kind cluster
        uses: helm/kind-action@v1.10.0
        if: steps.list-changed.outputs.changed == 'true'

      - name: Check if llmos-monitoring is in the list
        id: check-changed-list
        run: |
          if echo "${{ steps.list-changed.outputs.changed_list }}" | grep -q "llmos-monitoring"; then
            echo "llmos_monitoring_changed=true" >> "$GITHUB_ENV"
          else
            echo "llmos_monitoring_changed=false" >> "$GITHUB_ENV"
          fi
        if: steps.list-changed.outputs.changed == 'true'
      
      - name: Apply Gateway API CRDs
        run: kubectl apply -k https://github.com/kubernetes-sigs/gateway-api/config/crd
        if: env.llmos_monitoring_changed == 'true'
      
      - name: Run Monitoring Chart Test In Specified Namespace
        env:
          CHANGED_LIST: ${{ steps.list-changed.outputs.changed_list }}
        run: |
          kubectl create ns llmos-system && kubectl create ns llmos-monitoring-system && kubectl create ns llmos-dashboards \
          && kubectl create ns llmos-gpu-stack-system
          ct install --namespace llmos-monitoring-system --config .github/linters/ct.yaml
        if: env.llmos_monitoring_changed == 'true'
     
      - name: Run chart-testing (install)
        run: ct install --config .github/linters/ct.yaml
        env:
          CHANGED_LIST: ${{ steps.list-changed.outputs.changed_list }}
        if: env.llmos_monitoring_changed != 'true'
